### ISSUE TITLE
Grtting TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by maheshhraut** [IoannisNasios/solarsystem#2]
Tried example given in quickstart. Getting this error. any idea why?

Traceback (most recent call last):
  File "H:/Python Programs/tpp.py", line 5, in <module>
    planets_dict=H.planets()
TypeError: 'list' object is not callable

**Comment by IoannisNasios** [comment]
Hi maheshhraut,
I have just retried running the example given in quickstart and runs without any errors.
Did you call H=  solarsystem.Heliocentric(...) ?

```
planets_dict=H.planets()
import solarsystem
H = solarsystem.Heliocentric(year=2020, month=1, day=1, hour=12, minute=0 )
planets_dict=H.planets()
```

#my solarsystem version uppon my trial here is 0.1.5, last available at pypy
```
# pip install solarsystem
print(solarsystem.__version__)
# 0.1.5
```

**Comment by maheshhraut** [comment]
Working fine for Heliocentric system. Getting error for Geocentric system. Could you please check?
Thanks

**Comment by IoannisNasios** [comment]
if you want to use Geocentric system, try

```
import solarsystem
G = solarsystem.Geocentric(year=2020, month=1, day=1, hour=12, minute=0 )
object_list =G.objectnames()
```
In this list planet Earth is not present as the meaning is, all but Geo (=earth)

**Comment by maheshhraut** [comment]
Hi Loannis,

Thank you so much for your reply. I hope you are doing well in these though
times!

Regards,
Mahesh
